#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : os-ken
Version  : 1.0.0
Release  : 11
URL      : https://files.pythonhosted.org/packages/fc/62/c27db771f954cd44084aecbea28fb0580399eb2b03a5a7a1bbf3ac007b88/os-ken-1.0.0.tar.gz
Source0  : https://files.pythonhosted.org/packages/fc/62/c27db771f954cd44084aecbea28fb0580399eb2b03a5a7a1bbf3ac007b88/os-ken-1.0.0.tar.gz
Summary  : A component-based software defined networking framework for OpenStack.
Group    : Development/Tools
License  : Apache-2.0
Requires: os-ken-bin = %{version}-%{release}
Requires: os-ken-license = %{version}-%{release}
Requires: os-ken-python = %{version}-%{release}
Requires: os-ken-python3 = %{version}-%{release}
Requires: Routes
Requires: eventlet
Requires: msgpack
Requires: netaddr
Requires: oslo.config
Requires: ovs
Requires: pbr
Requires: six
Requires: tinyrpc
BuildRequires : Routes
BuildRequires : buildreq-distutils3
BuildRequires : eventlet
BuildRequires : msgpack
BuildRequires : netaddr
BuildRequires : oslo.config
BuildRequires : ovs
BuildRequires : pbr
BuildRequires : six
BuildRequires : tinyrpc

%description
os-ken
        ======
        
        A component-based software defined networking framework in OpenStack.
        
        This is a fork of the Ryu library tailored for OpenStack Neutron.

%package bin
Summary: bin components for the os-ken package.
Group: Binaries
Requires: os-ken-license = %{version}-%{release}

%description bin
bin components for the os-ken package.


%package license
Summary: license components for the os-ken package.
Group: Default

%description license
license components for the os-ken package.


%package python
Summary: python components for the os-ken package.
Group: Default
Requires: os-ken-python3 = %{version}-%{release}

%description python
python components for the os-ken package.


%package python3
Summary: python3 components for the os-ken package.
Group: Default
Requires: python3-core
Provides: pypi(os_ken)
Requires: pypi(eventlet)
Requires: pypi(msgpack)
Requires: pypi(netaddr)
Requires: pypi(oslo.config)
Requires: pypi(ovs)
Requires: pypi(pbr)
Requires: pypi(routes)
Requires: pypi(six)
Requires: pypi(tinyrpc)
Requires: pypi(webob)

%description python3
python3 components for the os-ken package.


%prep
%setup -q -n os-ken-1.0.0
cd %{_builddir}/os-ken-1.0.0

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1583538323
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/os-ken
cp %{_builddir}/os-ken-1.0.0/LICENSE %{buildroot}/usr/share/package-licenses/os-ken/294b43b2cec9919063be1a3b49e8722648424779
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/osken
/usr/bin/osken-manager

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/os-ken/294b43b2cec9919063be1a3b49e8722648424779

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
